---
- name: install apache & php
  remote_user: vamsip
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "Install apache2"
      package: name=apache2 state=present
    - name: "Install apache2-php5"
      package: name=libapache2-mod-php state=present
    - name: "Install php-cli"
      package: name=php-cli state=present
 #    - name: "Install php-mcrypt"
 #     package: name=php-mcrypt state=present
    - name: "Install php-gd"
      package: name=php-gd state=present
    - name: Install php-fpm
      package: name=php-fpm state=present
    - name: Install php-common
      package: name=php-common state=present
    - name: Install php-mbstring
      package: name=php-mbstring state=present
    - name: Install php-xmlrpc
      package: name=php-xmlrpc state=present
    - name: Install php-xml
      package: name=php-xml state=present
    - name: Install php-mysql
      package: name=php-mysql state=present
    - name: Install php zip
      package: name=php-zip state=present
    - name: Install php-curl
      package: name=php-curl state=present
