---
 - hosts: all
 
   vars:
         mysql_root_password: password
   tasks:
     - name: install mysql 
       become: true    
       apt: name=mysql update_cache=yes cache_valid_time=3600 state=present
     - name: start up the mysql service
       shell: "service mysql start"
     - name: ensure mysql is enabled to run on startup
       service: name=mysql state=started enabled=true
     - name: update mysql root password for all root accounts  
       mysql_user:  
         name: root  
         host: "{{ item }}"  
         password: "{{ mysql_root_password }}"  
         login_user: root  
         login_password: "{{ mysql_root_password }}"  
         check_implicit_admin: yes  
         priv: "*.*:ALL,GRANT"  
       with_items:  
       - "{{ ansible_hostname }}"  
       - 127.0.0.1  
       - ::1  
       - localhost 
     - name: Create a new database called wordpress
       mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: wordpress
        state: present

     - name: Configure new MySQL user called wp_user
       mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: wp_user
        password: Vamsi123@
        priv: 'wordpress.*:ALL'    
