---
  - name: install dependency packages
    ansible.builtin.apt:
      name: gnupg2,apt-transport-https,software-properties-common
      state: present
      update_cache: yes
      cache_valid_time: 3600

  - name: add grafana-gpg key
    apt_key:
      url: "https://packages.grafana.com/gpg.key"
      validate_certs: no 

  - name: add grafana-repository to apt
    apt_repository:
      repo: "deb https://packages.grafana.com/oss/deb stable main"
      state: present
      validate_certs: no

  - name: install grafana
    ansible.builtin.apt:
      name: grafana
      state: latest
      update_cache: yes
      cache_valid_time: 3600    

  - name: start service grafana-server
    systemd:
      name: grafana-server
      state: started
      enabled: yes

